//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_main
{
    using System;
    using System.Collections.Generic;
    
    public partial class kierunki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kierunki()
        {
            this.przedmioty = new HashSet<przedmioty>();
            this.zapisani_na_kierunek = new HashSet<zapisani_na_kierunek>();
        }
    
        public int ID { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> wydzial_id { get; set; }
        public bool tryb_stacjonarny { get; set; }
        public int rok_rozpoczecia { get; set; }
    
        public virtual wydzialy wydzialy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<przedmioty> przedmioty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zapisani_na_kierunek> zapisani_na_kierunek { get; set; }
    }
}
