//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_main
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_zajec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plan_zajec()
        {
            this.lista_obecnosci = new HashSet<lista_obecnosci>();
        }
    
        public int ID { get; set; }
        public Nullable<int> sala_id { get; set; }
        public Nullable<int> przedmiot_id { get; set; }
        public Nullable<int> prowadzacy_id { get; set; }
        public Nullable<System.DateTime> dzien { get; set; }
        public Nullable<bool> odbyte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lista_obecnosci> lista_obecnosci { get; set; }
        public virtual prowadzacy_przedmiot prowadzacy_przedmiot { get; set; }
        public virtual przedmioty przedmioty { get; set; }
        public virtual sale sale { get; set; }
    }
}
