//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_main
{
    using System;
    using System.Collections.Generic;
    
    public partial class prowadzacy_przedmiot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prowadzacy_przedmiot()
        {
            this.plan_zajec = new HashSet<plan_zajec>();
        }
    
        public int ID { get; set; }
        public Nullable<int> przedmiot_id { get; set; }
        public Nullable<int> prowadzacy_id { get; set; }
        public Nullable<bool> aktywny { get; set; }
    
        public virtual kadra kadra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plan_zajec> plan_zajec { get; set; }
        public virtual przedmioty przedmioty { get; set; }
    }
}
