//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PT_main
{
    using System;
    using System.Collections.Generic;
    
    public partial class zapisani_na_przedmiot
    {
        public int ID { get; set; }
        public Nullable<int> student_id { get; set; }
        public Nullable<int> przedmiot_id { get; set; }
    
        public virtual przedmioty przedmioty { get; set; }
        public virtual studenci studenci { get; set; }
    }
}
